apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: ${{ values.description | dump }}
  tags:
    - nodejs    
    - webapi
    - express
  
  links:
    - url: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}
      title: Repository
      icon: github

  annotations:
    # this could also be `url:<url>` if the documentation isn't in the same location
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner | dump }}
  system: ${{ values.system }}