site_name: ${{values.name | dump}}
site_description: ${{values.description | dump}}

nav:
  - Introduction: index.md
  - API Reference:
    - Overview: api.md
    - Endpoints: endpoints.md

plugins:
  - techdocs-core